[package]
name = "wikipedia"
version = "0.2.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]
license-file = "LICENSE"

description = "Access wikipedia articles from Rust"
readme = "README.md"
documentation = "https://seppo0010.github.io/wikipedia-rs/"

repository = "https://github.com/seppo0010/wikipedia-rs/"
keywords = ["wikipedia", "api"]

[features]
default = ["http-client"]
http-client = ["hyper", "url"]

[dependencies]
serde_json = "0.6.0"

[dependencies.hyper]
version = "0.6.13"
optional = true

[dependencies.url]
version = "0.2.37"
optional = true
