[package]
name = "wikipedia"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]

[features]
default = ["http-client"]
http-client = ["hyper", "url"]

[dependencies]
serde_json = "0.6.0"

[dependencies.hyper]
hyper = "0.6.13"
optional = true

[dependencies.url]
url = "0.2.37"
optional = true
